# Generated by Django 6.0.5 on 2026-06-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
