# Generated by Django 6.0.5 on 2026-06-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(default='trainers/default.jpg', upload_to='trainers/'),
            preserve_default=False,
        ),
    ]
